[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[provider]
cluster = "testnet"
wallet = "/home/pulse-aris/.config/solana/pulsaris-testnet/id.json"

[programs.testnet]
pulsaris_master_token = "H9KcwtZEukpbWjtCKTupph3XM6ZwJReUHb1Y4q4bD8H7"
pulsaris_category_vaults = "Gh4K4joEfrm2P3k1MHNBAWNobXWuuJHNNwFMpStiJVcK"
pulsaris_hedge_manager = "GyAkayDBE1XDiXYbukc7gGSi3ddZjPhP2aH8Lwmg2Hfs"
pulsaris_staking = "Cd281Df6HDi63JiEmeYR9cnVPm6g2eL8uDbG7TdWKwQS"

[registry]
url = "https://api.apr.dev"

[scripts]
initialize     = "cargo test --test initialize -- --nocapture --test-threads=1"
update_params  = "cargo test --test update_params -- --nocapture --test-threads=1"
test_all       = "cargo test -- --nocapture --test-threads=1"

[clusters]
localnet = "http://127.0.0.1:8899"
devnet   = "https://api.devnet.solana.com"
testnet  = "https://api.testnet.solana.com"
mainnet  = "https://api.mainnet-beta.solana.com"
