[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
pulsaris_staking = "DhGRyum7EN4q8V1yM8HmpYvgsM6TcqDozYBJTyGjHWsg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/pulse-aris/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
